---
name: PlatformIO CI

on:
  schedule:
    - cron: '0 21 * * 1-5'
  push:
    branches: ["master"]
    paths:
      - 'src/**/*'
      - 'include/**/*'
      - 'data/**/*'
      - '.github/**/*'
      - 'platformio.ini'
  pull_request:
    branches: ["master"]
    paths:
      - 'src/**/*'
      - 'include/**/*'
      - 'data/**/*'
      - 'platformio.ini'

jobs:
  build:
    runs-on: ubuntu-24.04
    strategy:
      matrix:
        example: [examples/absoluteXYZ.ino]
    steps:
    - uses: actions/checkout@v2
    - name: Cache pip
      uses: actions/cache@v3
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
        restore-keys: ${{ runner.os }}-pip-
    - name: Cache PlatformIO
      uses: actions/cache@v3
      with:
        path: ~/.platformio
        key: ${{ runner.os }}-${{ hashFiles('**/lockfiles') }}
    - name: Set up Python
      uses: actions/setup-python@v2
    - name: Install PlatformIO
      run: |
        python -m pip install --upgrade pip
        pip install --upgrade platformio
    - name: Run PlatformIO
      run: pio run
      env:
        PLATFORMIO_CI_SRC: ${{ matrix.example }}
    - name: Copy firmware
      run: |
        TYPE=`ls -l .pio/build/ | grep "^d" | awk '{print $9}'`
        for t in ${TYPE}; do
          mkdir -p ./firmware/${t}
          cp -r .pio/build/${t}/firmware.bin ./firmware/${t}/firmware.bin
        done
    - name: Commit changes
      uses: EndBug/add-and-commit@v9
      with:
        author_name: RootShell-coder
        author_email: Root.Shelling@gmail.com
        message: 'upd firmware'
        add: './firmware'
